#include "modular/dawnwalker/components/dawnwalker_component.dm"
#include "modular/dawnwalker/special_traits/dawnwalker_trait.dm"
#include "modular/dawnwalker/status_effects/dawnwalker_buffs.dm"
#include "modular/dawnwalker/status_effects/dawnwalker_debuffs.dm"
#include "modular/dawnwalker/stress/dawnwalker_stress.dm"
#include "modular/dawnwalker/mob/dawnwalker_human.dm"
